// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Scalingo/go-scalingo/v5 (interfaces: NotifiersService)

// Package scalingomock is a generated GoMock package.
package scalingomock

import (
	context "context"
	reflect "reflect"

	scalingo "github.com/Scalingo/go-scalingo/v5"
	gomock "github.com/golang/mock/gomock"
)

// MockNotifiersService is a mock of NotifiersService interface.
type MockNotifiersService struct {
	ctrl     *gomock.Controller
	recorder *MockNotifiersServiceMockRecorder
}

// MockNotifiersServiceMockRecorder is the mock recorder for MockNotifiersService.
type MockNotifiersServiceMockRecorder struct {
	mock *MockNotifiersService
}

// NewMockNotifiersService creates a new mock instance.
func NewMockNotifiersService(ctrl *gomock.Controller) *MockNotifiersService {
	mock := &MockNotifiersService{ctrl: ctrl}
	mock.recorder = &MockNotifiersServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotifiersService) EXPECT() *MockNotifiersServiceMockRecorder {
	return m.recorder
}

// NotifierByID mocks base method.
func (m *MockNotifiersService) NotifierByID(arg0 context.Context, arg1, arg2 string) (*scalingo.Notifier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifierByID", arg0, arg1, arg2)
	ret0, _ := ret[0].(*scalingo.Notifier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NotifierByID indicates an expected call of NotifierByID.
func (mr *MockNotifiersServiceMockRecorder) NotifierByID(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifierByID", reflect.TypeOf((*MockNotifiersService)(nil).NotifierByID), arg0, arg1, arg2)
}

// NotifierDestroy mocks base method.
func (m *MockNotifiersService) NotifierDestroy(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifierDestroy", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifierDestroy indicates an expected call of NotifierDestroy.
func (mr *MockNotifiersServiceMockRecorder) NotifierDestroy(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifierDestroy", reflect.TypeOf((*MockNotifiersService)(nil).NotifierDestroy), arg0, arg1, arg2)
}

// NotifierProvision mocks base method.
func (m *MockNotifiersService) NotifierProvision(arg0 context.Context, arg1 string, arg2 scalingo.NotifierParams) (*scalingo.Notifier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifierProvision", arg0, arg1, arg2)
	ret0, _ := ret[0].(*scalingo.Notifier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NotifierProvision indicates an expected call of NotifierProvision.
func (mr *MockNotifiersServiceMockRecorder) NotifierProvision(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifierProvision", reflect.TypeOf((*MockNotifiersService)(nil).NotifierProvision), arg0, arg1, arg2)
}

// NotifierUpdate mocks base method.
func (m *MockNotifiersService) NotifierUpdate(arg0 context.Context, arg1, arg2 string, arg3 scalingo.NotifierParams) (*scalingo.Notifier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifierUpdate", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*scalingo.Notifier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NotifierUpdate indicates an expected call of NotifierUpdate.
func (mr *MockNotifiersServiceMockRecorder) NotifierUpdate(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifierUpdate", reflect.TypeOf((*MockNotifiersService)(nil).NotifierUpdate), arg0, arg1, arg2, arg3)
}

// NotifiersList mocks base method.
func (m *MockNotifiersService) NotifiersList(arg0 context.Context, arg1 string) (scalingo.Notifiers, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifiersList", arg0, arg1)
	ret0, _ := ret[0].(scalingo.Notifiers)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NotifiersList indicates an expected call of NotifiersList.
func (mr *MockNotifiersServiceMockRecorder) NotifiersList(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifiersList", reflect.TypeOf((*MockNotifiersService)(nil).NotifiersList), arg0, arg1)
}
